### ISSUE TITLE
 sim.Circuit is not a constructor

### ISSUE THREAD

**Issue by ericmx** [Qiskit/qiskit-js#20]
### Environment:

- **Qiskit-js 0.3.0**:
- **Node 10.7.0**:
- **macOS High Sierra 10.13.6**:

### What is the current behavior?
TypeError: sim.Circuit is not a constructor thrown

TypeError: sim.Circuit is not a constructor
    at Object.<anonymous> (/Users/ericmay/Development/work/simulator_test.js:18:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)

### Steps to reproduce the problem
Run the example program on the Readme page after installing qiskit-js/sim 

### What is the expected behavior?
The sample program should execute without the TypeError.
https://github.com/Qiskit/qiskit-js/tree/master/packages/qiskit-sim

### Suggested solutions

TY!

**Comment by jesusprubio** [comment]
Hi, sorry for the delay. I think it was an inconsistency between the published version and the master branch here.

I've published a new version with much more fixes and improvements right now, could you please recheck with last sources or npm packages?

Thanks for the feedback. :smile:

**Comment by ericmx** [comment]
It appears to work now for me. Thanks for your hard work! My goal was to just start with the simple examples from the project and get those to work, and now it appears that the simulator works out of the box from the example code I have [here](https://github.com/Qiskit/qiskit-js/tree/master/packages/qiskit-sim).

I am going to try the IBM Q Experience next (Qiskit-js/cloud) and see if I can get it to work naively.

Thank you once again!

**Comment by jesusprubio** [comment]
Thanks again, and please reach me with any other problem, doubt or suggestion :).
