### ISSUE TITLE
can't run --help

### ISSUE THREAD

**Issue by omarcostahamido** [Qiskit/qiskit-js#30]
### Environment (please complete the following information):
I try to run: `qiskitjs --help`
and get:

```
module.js:540
    throw err;
    ^

Error: Cannot find module 'jsqubits/lib/jsqubits'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Omar\AppData\Roaming\npm\node_modules\@qiskit\sdk\node_modules\@qiskit\devs-js\lib\factor.js:17:18)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```

- **Qiskit.js version**: 0.5.0
- **Node.js version**:8.9.4
- **Operating system**:Win 10 x64 updated 17134

**Comment by omarcostahamido** [comment]
Same thing on mac (mojave)
node 10.15.3

**Comment by jesusprubio** [comment]
Thank you for the feedback. We've just published a new release (0.6.1) which fixes this problem and improves other things.

https://github.com/Qiskit/qiskit-js/releases/tag/v0.6

Could you please confirm if is it working for you now? :smile:

**Comment by omarcostahamido** [comment]
Yes! It is working. Thank you so much.
Now I need to learn how to use it 🤣

**Comment by jesusprubio** [comment]
Please ask any doubt, too much different parts are involved. :)
