### ISSUE TITLE
not able to run test file

### ISSUE THREAD

**Issue by omarcostahamido** [Qiskit/qiskit-js#63]
### Environment (please complete the following information):

- **Qiskit.js version**:
0.8.0 (actually also a direct copy of the github folder structure)
- **Node.js version**:
10.15.3
- **Operating system**:
mojave

### What is the current behavior?
How am I supposed to be able to run the test files?
this is what happens when I try to run qiskit-qasm/test/functional/parser.test.js
<details><summary>terminal</summary>
<p>

```
$ node parser.test.js 
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'jison'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/omar/Documents/RESEARCH/Experiments/qiskit-js-master(2019-05-04)/packages/qiskit-qasm/lib/Parser.js:12:15)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

</p>
</details>

### Steps to reproduce the problem
copied github structure and then run js file.

### What is the expected behavior?
not an error (?)

**Comment by omarcostahamido** [comment]
ok, admittedly there was one big newbie mistake on my part: forgot to ```install``` xD
Now, after ```npm i```, I'm still experiencing this:
<details><summary>terminal</summary>
<p>


```
$ node parser.test.js 
/Users/omar/Documents/RESEARCH/Experiments/github_qiskit-js-master(2019-05-04)/node_modules/snap-shot-it/src/index.js:66
global.beforeEach(function () {
       ^

TypeError: global.beforeEach is not a function
    at Object.<anonymous> (/Users/omar/Documents/RESEARCH/Experiments/github_qiskit-js-master(2019-05-04)/node_modules/snap-shot-it/src/index.js:66:8)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/omar/Documents/RESEARCH/Experiments/github_qiskit-js-master(2019-05-04)/utils-test/index.js:16:14)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
```


</p>
</details>

**Comment by danbev** [comment]
@omarcostahamido The tests are using [mocha](https://mochajs.org/) and need be run through it. For example, you can use npx if you don't have mocha installed globally:
```console
$ npx mocha test/functional/parser.test.js
```
There is also a `test` run script in package.json which can be run:
```console
$ npm install mocha -g
$ npm test
```

**Comment by jesusprubio** [comment]
Please take a look to this: https://github.com/Qiskit/qiskit-js/pull/61#issuecomment-489514700

**Comment by jesusprubio** [comment]
About the mocha setup I've just explained it here for a different dependency: https://github.com/IBM/kui/pull/1303

So `npm i` and `npm test` should be enough.

**Comment by danbev** [comment]
@jesusprubio @omarcostahamido Could this issue be closed now perhaps?

**Comment by omarcostahamido** [comment]
@danbev Sure.
