### ISSUE TITLE
webpack example issues

### ISSUE THREAD

**Issue by omarcostahamido** [Qiskit/qiskit-js#86]
### What is the expected behavior?
I'm receiving this if I try to run the example on a copy of the webpack folder by itself:
<details><summary>terminal</summary>

```
Omars-MBP:Downloads omar$  cd webpack
Omars-MBP:webpack omar$  npm i

> fsevents@1.2.9 install /Users/omar/Downloads/webpack/node_modules/fsevents
> node install

node-pre-gyp WARN Using needle for node-pre-gyp https download 
[fsevents] Success: "/Users/omar/Downloads/webpack/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote
added 649 packages from 374 contributors and audited 7089 packages in 10.044s
found 0 vulnerabilities

Omars-MBP:webpack omar$  npm run init

> qiskit-webpack-example@0.0.1 init /Users/omar/Downloads/webpack
> mkdir node_modules/@qiskit/qasm/core ; cp ../../packages/qiskit-qasm/core/qelib1.inc node_modules/@qiskit/qasm/core

cp: ../../packages/qiskit-qasm/core/qelib1.inc: No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! qiskit-webpack-example@0.0.1 init: `mkdir node_modules/@qiskit/qasm/core ; cp ../../packages/qiskit-qasm/core/qelib1.inc node_modules/@qiskit/qasm/core`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the qiskit-webpack-example@0.0.1 init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/omar/.npm/_logs/2019-08-30T23_27_03_547Z-debug.log
```

</details>

<details><summary>log</summary>

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/Users/omar/.npm-global/bin/npm',
1 verbose cli   'run',
1 verbose cli   'init' ]
2 info using npm@6.9.0
3 info using node@v10.15.3
4 verbose run-script [ 'preinit', 'init', 'postinit' ]
5 info lifecycle qiskit-webpack-example@0.0.1~preinit: qiskit-webpack-example@0.0.1
6 info lifecycle qiskit-webpack-example@0.0.1~init: qiskit-webpack-example@0.0.1
7 verbose lifecycle qiskit-webpack-example@0.0.1~init: unsafe-perm in lifecycle true
8 verbose lifecycle qiskit-webpack-example@0.0.1~init: PATH: /Users/omar/.npm-global/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/omar/Downloads/webpack/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:~/.npm-global/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:~/.npm-global/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools
9 verbose lifecycle qiskit-webpack-example@0.0.1~init: CWD: /Users/omar/Downloads/webpack
10 silly lifecycle qiskit-webpack-example@0.0.1~init: Args: [ '-c',
10 silly lifecycle   'mkdir node_modules/@qiskit/qasm/core ; cp ../../packages/qiskit-qasm/core/qelib1.inc node_modules/@qiskit/qasm/core' ]
11 silly lifecycle qiskit-webpack-example@0.0.1~init: Returned: code: 1  signal: null
12 info lifecycle qiskit-webpack-example@0.0.1~init: Failed to exec init script
13 verbose stack Error: qiskit-webpack-example@0.0.1 init: `mkdir node_modules/@qiskit/qasm/core ; cp ../../packages/qiskit-qasm/core/qelib1.inc node_modules/@qiskit/qasm/core`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/omar/.npm-global/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/omar/.npm-global/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid qiskit-webpack-example@0.0.1
15 verbose cwd /Users/omar/Downloads/webpack
16 verbose Darwin 18.7.0
17 verbose argv "/usr/local/bin/node" "/Users/omar/.npm-global/bin/npm" "run" "init"
18 verbose node v10.15.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error qiskit-webpack-example@0.0.1 init: `mkdir node_modules/@qiskit/qasm/core ; cp ../../packages/qiskit-qasm/core/qelib1.inc node_modules/@qiskit/qasm/core`
22 error Exit status 1
23 error Failed at the qiskit-webpack-example@0.0.1 init script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

</details>

could you make so that it doesn't need to change/access files from the main repo and work independently?

**Comment by danbev** [comment]
> could you make so that it doesn't need to change/access files from the main repo and work independently?

Let me remove that from the example and if we then do a new release this copying will no longer be needed.
